SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

CREATE TABLE IF NOT EXISTS activity_config (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  activity_code VARCHAR(64) NOT NULL UNIQUE,
  activity_name VARCHAR(128) NOT NULL,
  status VARCHAR(16) NOT NULL DEFAULT 'draft',
  start_at DATETIME NULL,
  end_at DATETIME NULL,
  daily_default_chance INT NOT NULL DEFAULT 1,
  daily_share_bonus_limit INT NOT NULL DEFAULT 3,
  share_target INT NOT NULL DEFAULT 5,
  checkin_target INT NOT NULL DEFAULT 7,
  grand_prize_name VARCHAR(128) NOT NULL DEFAULT '985 和牛礼盒',
  rules_text JSON NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CHECK (status IN ('draft', 'active', 'paused', 'ended')),
  CHECK (daily_default_chance >= 0),
  CHECK (daily_share_bonus_limit >= 0),
  CHECK (share_target >= 0),
  CHECK (checkin_target >= 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS activity_asset_config (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  activity_code VARCHAR(64) NOT NULL,
  asset_key VARCHAR(96) NOT NULL,
  asset_type VARCHAR(32) NOT NULL,
  asset_url VARCHAR(512) NOT NULL,
  fallback_url VARCHAR(512) NULL,
  title VARCHAR(128) NULL,
  status VARCHAR(16) NOT NULL DEFAULT 'enabled',
  sort_order INT NOT NULL DEFAULT 0,
  ext_json JSON NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uk_activity_asset (activity_code, asset_key),
  KEY idx_activity_asset_status (activity_code, asset_type, status, sort_order),
  CONSTRAINT fk_asset_activity FOREIGN KEY (activity_code) REFERENCES activity_config(activity_code),
  CHECK (asset_type IN ('qrcode', 'reward_image', 'product_image', 'banner', 'background', 'icon', 'other')),
  CHECK (status IN ('enabled', 'disabled'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS product_recommend_config (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  activity_code VARCHAR(64) NOT NULL,
  product_code VARCHAR(64) NOT NULL,
  product_id VARCHAR(96) NULL,
  product_name VARCHAR(128) NOT NULL,
  product_desc VARCHAR(255) NULL,
  product_image_url VARCHAR(512) NULL,
  price_text VARCHAR(64) NULL,
  action_type VARCHAR(64) NOT NULL DEFAULT 'mini_program_product_detail',
  action_target VARCHAR(512) NOT NULL,
  status VARCHAR(16) NOT NULL DEFAULT 'enabled',
  sort_order INT NOT NULL DEFAULT 0,
  ext_json JSON NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uk_product_recommend (activity_code, product_code),
  KEY idx_product_recommend_status (activity_code, status, sort_order),
  CONSTRAINT fk_product_activity FOREIGN KEY (activity_code) REFERENCES activity_config(activity_code),
  CHECK (status IN ('enabled', 'disabled'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS reward_config (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  activity_code VARCHAR(64) NOT NULL,
  reward_code VARCHAR(64) NOT NULL,
  reward_type VARCHAR(32) NOT NULL,
  reward_name VARCHAR(128) NOT NULL,
  reward_title VARCHAR(128) NULL,
  reward_desc VARCHAR(255) NULL,
  reward_amount_text VARCHAR(64) NULL,
  reward_image_url VARCHAR(512) NULL,
  button_text VARCHAR(64) NULL,
  action_type VARCHAR(64) NOT NULL DEFAULT 'placeholder',
  action_target VARCHAR(512) NULL,
  is_grand_prize TINYINT(1) NOT NULL DEFAULT 0,
  status VARCHAR(16) NOT NULL DEFAULT 'enabled',
  sort_order INT NOT NULL DEFAULT 0,
  ext_json JSON NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uk_reward_config (activity_code, reward_code),
  KEY idx_reward_config_status (activity_code, reward_type, status, sort_order),
  CONSTRAINT fk_reward_activity FOREIGN KEY (activity_code) REFERENCES activity_config(activity_code),
  CHECK (reward_type IN ('coupon', 'discount_coupon', 'product', 'grand_prize', 'other')),
  CHECK (is_grand_prize IN (0, 1)),
  CHECK (status IN ('enabled', 'disabled'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS draw_result_config (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  activity_code VARCHAR(64) NOT NULL,
  result_code VARCHAR(64) NOT NULL,
  result_level VARCHAR(64) NULL,
  result_title VARCHAR(128) NOT NULL,
  main_text TEXT NOT NULL,
  good_text TEXT NULL,
  avoid_text TEXT NULL,
  explain_title VARCHAR(128) NULL,
  explain_content TEXT NULL,
  tags_json JSON NULL,
  product_code VARCHAR(64) NULL,
  reward_code VARCHAR(64) NULL,
  status VARCHAR(16) NOT NULL DEFAULT 'enabled',
  sort_order INT NOT NULL DEFAULT 0,
  ext_json JSON NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uk_draw_result_config (activity_code, result_code),
  KEY idx_draw_result_status (activity_code, status, sort_order),
  CONSTRAINT fk_draw_result_activity FOREIGN KEY (activity_code) REFERENCES activity_config(activity_code),
  CONSTRAINT fk_draw_result_product FOREIGN KEY (activity_code, product_code) REFERENCES product_recommend_config(activity_code, product_code),
  CONSTRAINT fk_draw_result_reward FOREIGN KEY (activity_code, reward_code) REFERENCES reward_config(activity_code, reward_code),
  CHECK (status IN ('enabled', 'disabled'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS activity_user (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  activity_code VARCHAR(64) NOT NULL,
  user_key VARCHAR(128) NOT NULL,
  external_user_id VARCHAR(128) NULL,
  openid VARCHAR(128) NULL,
  unionid VARCHAR(128) NULL,
  nickname VARCHAR(128) NULL,
  avatar_url VARCHAR(512) NULL,
  source_channel VARCHAR(64) NULL,
  status VARCHAR(16) NOT NULL DEFAULT 'active',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uk_activity_user (activity_code, user_key),
  KEY idx_activity_user_external (activity_code, external_user_id, openid, unionid),
  CONSTRAINT fk_user_activity FOREIGN KEY (activity_code) REFERENCES activity_config(activity_code),
  CHECK (status IN ('active', 'blocked'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS activity_session (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  activity_code VARCHAR(64) NOT NULL,
  user_id BIGINT NOT NULL,
  session_token VARCHAR(128) NOT NULL UNIQUE,
  source_page VARCHAR(64) NULL,
  source_channel VARCHAR(64) NULL,
  source_share_token VARCHAR(128) NULL,
  source_user_id BIGINT NULL,
  ip_address VARCHAR(64) NULL,
  user_agent VARCHAR(512) NULL,
  status VARCHAR(16) NOT NULL DEFAULT 'active',
  invite_status VARCHAR(16) NOT NULL DEFAULT 'none',
  assist_completed_at DATETIME NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  KEY idx_activity_session_user (activity_code, user_id, created_at),
  KEY idx_activity_session_invite (activity_code, invite_status, source_share_token),
  CONSTRAINT fk_session_activity FOREIGN KEY (activity_code) REFERENCES activity_config(activity_code),
  CONSTRAINT fk_session_user FOREIGN KEY (user_id) REFERENCES activity_user(id),
  CONSTRAINT fk_session_source_user FOREIGN KEY (source_user_id) REFERENCES activity_user(id),
  CHECK (status IN ('active', 'expired')),
  CHECK (invite_status IN ('none', 'pending', 'completed', 'invalid'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS user_daily_state (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  activity_code VARCHAR(64) NOT NULL,
  user_id BIGINT NOT NULL,
  biz_date DATE NOT NULL,
  base_draw_chance INT NOT NULL DEFAULT 1,
  extra_draw_chance INT NOT NULL DEFAULT 0,
  used_draw_count INT NOT NULL DEFAULT 0,
  remaining_draw_count INT NOT NULL DEFAULT 1,
  share_reward_count_today INT NOT NULL DEFAULT 0,
  checked_in_today TINYINT(1) NOT NULL DEFAULT 0,
  status VARCHAR(16) NOT NULL DEFAULT 'active',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uk_user_daily_state (activity_code, user_id, biz_date),
  KEY idx_user_daily_state_date (activity_code, biz_date, status),
  CONSTRAINT fk_daily_activity FOREIGN KEY (activity_code) REFERENCES activity_config(activity_code),
  CONSTRAINT fk_daily_user FOREIGN KEY (user_id) REFERENCES activity_user(id),
  CHECK (base_draw_chance >= 0),
  CHECK (extra_draw_chance >= 0),
  CHECK (used_draw_count >= 0),
  CHECK (remaining_draw_count >= 0),
  CHECK (share_reward_count_today >= 0),
  CHECK (checked_in_today IN (0, 1)),
  CHECK (status IN ('active', 'locked'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS draw_record (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  activity_code VARCHAR(64) NOT NULL,
  user_id BIGINT NOT NULL,
  session_id BIGINT NULL,
  draw_no VARCHAR(128) NOT NULL UNIQUE,
  result_code VARCHAR(64) NOT NULL,
  biz_date DATE NOT NULL,
  chance_cost INT NOT NULL DEFAULT 1,
  draw_status VARCHAR(16) NOT NULL DEFAULT 'success',
  source_share_token VARCHAR(128) NULL,
  idempotency_key VARCHAR(128) NULL,
  result_level_snapshot VARCHAR(64) NULL,
  result_title_snapshot VARCHAR(128) NULL,
  main_text_snapshot TEXT NULL,
  good_text_snapshot TEXT NULL,
  avoid_text_snapshot TEXT NULL,
  explain_title_snapshot VARCHAR(128) NULL,
  explain_content_snapshot TEXT NULL,
  result_summary_json JSON NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uk_draw_idempotency (activity_code, user_id, idempotency_key),
  KEY idx_draw_record_user_date (activity_code, user_id, biz_date, created_at),
  CONSTRAINT fk_draw_activity FOREIGN KEY (activity_code) REFERENCES activity_config(activity_code),
  CONSTRAINT fk_draw_user FOREIGN KEY (user_id) REFERENCES activity_user(id),
  CONSTRAINT fk_draw_session FOREIGN KEY (session_id) REFERENCES activity_session(id),
  CONSTRAINT fk_draw_result FOREIGN KEY (activity_code, result_code) REFERENCES draw_result_config(activity_code, result_code),
  CHECK (chance_cost > 0),
  CHECK (draw_status IN ('success', 'failed', 'cancelled'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS draw_chance_log (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  activity_code VARCHAR(64) NOT NULL,
  user_id BIGINT NOT NULL,
  log_no VARCHAR(128) NOT NULL UNIQUE,
  biz_date DATE NOT NULL,
  change_type VARCHAR(32) NOT NULL,
  chance_delta INT NOT NULL,
  chance_before INT NOT NULL DEFAULT 0,
  chance_after INT NOT NULL DEFAULT 0,
  source_type VARCHAR(64) NULL,
  source_id VARCHAR(128) NULL,
  idempotency_key VARCHAR(128) NULL,
  remark VARCHAR(255) NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE KEY uk_chance_idempotency (activity_code, user_id, idempotency_key),
  KEY idx_draw_chance_user_date (activity_code, user_id, biz_date, change_type, created_at),
  CONSTRAINT fk_chance_activity FOREIGN KEY (activity_code) REFERENCES activity_config(activity_code),
  CONSTRAINT fk_chance_user FOREIGN KEY (user_id) REFERENCES activity_user(id),
  CHECK (change_type IN ('daily_default', 'share_bonus', 'draw_consume', 'admin_adjust', 'rollback')),
  CHECK (chance_delta <> 0),
  CHECK (chance_before >= 0),
  CHECK (chance_after >= 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS checkin_record (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  activity_code VARCHAR(64) NOT NULL,
  user_id BIGINT NOT NULL,
  draw_id BIGINT NOT NULL,
  biz_date DATE NOT NULL,
  lit_day_no INT NULL,
  status VARCHAR(16) NOT NULL DEFAULT 'valid',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uk_checkin_daily (activity_code, user_id, biz_date),
  CONSTRAINT fk_checkin_activity FOREIGN KEY (activity_code) REFERENCES activity_config(activity_code),
  CONSTRAINT fk_checkin_user FOREIGN KEY (user_id) REFERENCES activity_user(id),
  CONSTRAINT fk_checkin_draw FOREIGN KEY (draw_id) REFERENCES draw_record(id),
  CHECK (lit_day_no IS NULL OR lit_day_no > 0),
  CHECK (status IN ('valid', 'invalid'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS share_record (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  activity_code VARCHAR(64) NOT NULL,
  user_id BIGINT NOT NULL,
  session_id BIGINT NULL,
  share_token VARCHAR(128) NOT NULL UNIQUE,
  biz_date DATE NOT NULL,
  share_channel VARCHAR(64) NULL,
  share_status VARCHAR(16) NOT NULL DEFAULT 'created',
  reward_granted TINYINT(1) NOT NULL DEFAULT 0,
  reward_chance_delta INT NOT NULL DEFAULT 0,
  idempotency_key VARCHAR(128) NULL,
  completed_at DATETIME NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uk_share_idempotency (activity_code, user_id, idempotency_key),
  KEY idx_share_record_user_date (activity_code, user_id, biz_date, created_at),
  CONSTRAINT fk_share_activity FOREIGN KEY (activity_code) REFERENCES activity_config(activity_code),
  CONSTRAINT fk_share_user FOREIGN KEY (user_id) REFERENCES activity_user(id),
  CONSTRAINT fk_share_session FOREIGN KEY (session_id) REFERENCES activity_session(id),
  CHECK (share_status IN ('created', 'completed', 'cancelled')),
  CHECK (reward_granted IN (0, 1)),
  CHECK (reward_chance_delta >= 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS share_assist_record (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  activity_code VARCHAR(64) NOT NULL,
  share_record_id BIGINT NOT NULL,
  share_token VARCHAR(128) NOT NULL,
  sharer_user_id BIGINT NOT NULL,
  assister_user_id BIGINT NOT NULL,
  assister_session_id BIGINT NULL,
  draw_id BIGINT NOT NULL,
  biz_date DATE NOT NULL,
  assist_status VARCHAR(16) NOT NULL DEFAULT 'completed',
  invalid_reason VARCHAR(255) NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uk_share_assist_token_user (activity_code, share_token, assister_user_id),
  UNIQUE KEY uk_share_assist_sharer_user (activity_code, sharer_user_id, assister_user_id),
  KEY idx_share_assist_sharer (activity_code, sharer_user_id, created_at),
  CONSTRAINT fk_assist_activity FOREIGN KEY (activity_code) REFERENCES activity_config(activity_code),
  CONSTRAINT fk_assist_share FOREIGN KEY (share_record_id) REFERENCES share_record(id),
  CONSTRAINT fk_assist_sharer FOREIGN KEY (sharer_user_id) REFERENCES activity_user(id),
  CONSTRAINT fk_assist_assister FOREIGN KEY (assister_user_id) REFERENCES activity_user(id),
  CONSTRAINT fk_assist_session FOREIGN KEY (assister_session_id) REFERENCES activity_session(id),
  CONSTRAINT fk_assist_draw FOREIGN KEY (draw_id) REFERENCES draw_record(id),
  CHECK (assist_status IN ('completed', 'invalid'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS reward_claim_record (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  activity_code VARCHAR(64) NOT NULL,
  user_id BIGINT NOT NULL,
  session_id BIGINT NULL,
  draw_id BIGINT NULL,
  reward_code VARCHAR(64) NOT NULL,
  claim_no VARCHAR(128) NOT NULL UNIQUE,
  claim_status VARCHAR(16) NOT NULL DEFAULT 'success',
  claim_channel VARCHAR(64) NULL,
  reward_snapshot_json JSON NULL,
  action_type VARCHAR(64) NULL,
  action_target VARCHAR(512) NULL,
  idempotency_key VARCHAR(128) NULL,
  receiver_mobile VARCHAR(32) NULL,
  receiver_mobile_masked VARCHAR(32) NULL,
  claim_token VARCHAR(128) NULL,
  coupon_issue_status VARCHAR(32) NOT NULL DEFAULT 'pending',
  coupon_issue_error VARCHAR(512) NULL,
  external_member_id VARCHAR(128) NULL,
  biz_date DATE NOT NULL,
  claimed_at DATETIME NULL,
  use_status VARCHAR(16) NOT NULL DEFAULT 'unused',
  used_at DATETIME NULL,
  expire_at DATETIME NULL,
  external_coupon_id VARCHAR(128) NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uk_reward_claim_draw_reward (activity_code, user_id, draw_id, reward_code),
  UNIQUE KEY uk_reward_claim_idempotency (activity_code, user_id, idempotency_key),
  UNIQUE KEY uk_reward_claim_token (activity_code, claim_token),
  KEY idx_reward_claim_user (activity_code, user_id, claim_status, created_at),
  KEY idx_reward_claim_use_status (activity_code, user_id, use_status, expire_at),
  KEY idx_reward_claim_mobile (activity_code, receiver_mobile),
  KEY idx_reward_claim_coupon_issue (activity_code, coupon_issue_status, created_at),
  CONSTRAINT fk_claim_activity FOREIGN KEY (activity_code) REFERENCES activity_config(activity_code),
  CONSTRAINT fk_claim_user FOREIGN KEY (user_id) REFERENCES activity_user(id),
  CONSTRAINT fk_claim_session FOREIGN KEY (session_id) REFERENCES activity_session(id),
  CONSTRAINT fk_claim_draw FOREIGN KEY (draw_id) REFERENCES draw_record(id),
  CONSTRAINT fk_claim_reward FOREIGN KEY (activity_code, reward_code) REFERENCES reward_config(activity_code, reward_code),
  CHECK (claim_status IN ('success', 'pending', 'failed', 'cancelled')),
  CHECK (use_status IN ('unused', 'used', 'expired', 'locked')),
  CHECK (coupon_issue_status IN ('pending', 'issued', 'failed', 'skipped'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS grand_prize_qualification (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  activity_code VARCHAR(64) NOT NULL,
  user_id BIGINT NOT NULL,
  qualify_status VARCHAR(32) NOT NULL DEFAULT 'not_qualified',
  qualify_type VARCHAR(16) NOT NULL DEFAULT 'none',
  shared_count INT NOT NULL DEFAULT 0,
  lit_days INT NOT NULL DEFAULT 0,
  lottery_no VARCHAR(128) UNIQUE,
  lottery_status VARCHAR(32) NOT NULL DEFAULT 'pending',
  qrcode_id VARCHAR(128) NULL,
  qrcode_url VARCHAR(512) NULL,
  qualified_at DATETIME NULL,
  used_at DATETIME NULL,
  qualification_source_type VARCHAR(64) NULL,
  qualification_source_id VARCHAR(128) NULL,
  qualification_snapshot_json JSON NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uk_grand_prize_user (activity_code, user_id),
  KEY idx_grand_prize_status (activity_code, qualify_status, lottery_status),
  KEY idx_grand_prize_source (activity_code, qualification_source_type, qualification_source_id),
  CONSTRAINT fk_grand_prize_activity FOREIGN KEY (activity_code) REFERENCES activity_config(activity_code),
  CONSTRAINT fk_grand_prize_user FOREIGN KEY (user_id) REFERENCES activity_user(id),
  CHECK (qualify_status IN ('not_qualified', 'qualified', 'used', 'expired')),
  CHECK (qualify_type IN ('none', 'share', 'checkin', 'both')),
  CHECK (shared_count >= 0),
  CHECK (lit_days >= 0),
  CHECK (lottery_status IN ('pending', 'waiting_draw', 'drawn', 'won', 'not_won'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS tracking_event (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  activity_code VARCHAR(64) NULL,
  user_id BIGINT NULL,
  session_token VARCHAR(128) NULL,
  page_code VARCHAR(64) NULL,
  event_name VARCHAR(128) NOT NULL,
  event_payload JSON NULL,
  client_time DATETIME NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  KEY idx_tracking_event_name (activity_code, event_name, created_at),
  CONSTRAINT fk_tracking_activity FOREIGN KEY (activity_code) REFERENCES activity_config(activity_code),
  CONSTRAINT fk_tracking_user FOREIGN KEY (user_id) REFERENCES activity_user(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

SET FOREIGN_KEY_CHECKS = 1;
