from __future__ import annotations

import argparse
import os
import re
import subprocess
from dataclasses import dataclass
from pathlib import Path


REQUIRED_MYSQL_SCRIPT_NAMES = (
    "001_init_activity_tables.sql",
    "002_seed_basic_mock_config.sql",
)

MYSQL_IDENTIFIER_PATTERN = re.compile(r"^[A-Za-z_][A-Za-z0-9_]*$")
CREATE_TABLE_PATTERN = re.compile(
    r"CREATE\s+TABLE\s+IF\s+NOT\s+EXISTS\s+`?([A-Za-z_][A-Za-z0-9_]*)`?",
    re.IGNORECASE,
)


@dataclass(frozen=True)
class MysqlPrepareConfig:
    database: str = "gaokao_h5"
    host: str = "127.0.0.1"
    port: int = 3306
    user: str = "root"
    password: str = ""
    client: str = "mysql"

    @classmethod
    def from_env(cls) -> "MysqlPrepareConfig":
        return cls(
            database=os.environ.get("GAOKAO_H5_MYSQL_DATABASE", cls.database),
            host=os.environ.get("GAOKAO_H5_MYSQL_HOST", cls.host),
            port=int(os.environ.get("GAOKAO_H5_MYSQL_PORT", str(cls.port))),
            user=os.environ.get("GAOKAO_H5_MYSQL_USER", cls.user),
            password=os.environ.get("GAOKAO_H5_MYSQL_PASSWORD", cls.password),
            client=os.environ.get("GAOKAO_H5_MYSQL_CLIENT", cls.client),
        )

    def mysql_database_identifier(self) -> str:
        if not MYSQL_IDENTIFIER_PATTERN.fullmatch(self.database):
            raise ValueError(
                "GAOKAO_H5_MYSQL_DATABASE must be a plain MySQL identifier "
                "(letters, numbers, underscores; cannot start with a number)"
            )
        return self.database


def collect_mysql_scripts(root_dir: Path) -> list[Path]:
    mysql_dir = root_dir / "database" / "mysql"
    scripts = [mysql_dir / script_name for script_name in REQUIRED_MYSQL_SCRIPT_NAMES]
    missing = [str(script) for script in scripts if not script.exists()]
    if missing:
        raise FileNotFoundError("Missing MySQL bootstrap script(s): " + ", ".join(missing))
    return scripts


def extract_create_table_names(sql: str) -> list[str]:
    return CREATE_TABLE_PATTERN.findall(sql)


def build_bootstrap_sql(root_dir: Path, config: MysqlPrepareConfig) -> str:
    database = config.mysql_database_identifier()
    lines = [
        "-- Generated by scripts/prepare_mysql.py",
        "-- Safe to inspect with --dry-run before executing in MySQL.",
        "SET NAMES utf8mb4;",
        f"CREATE DATABASE IF NOT EXISTS `{database}` CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;",
        f"USE `{database}`;",
    ]
    for script in collect_mysql_scripts(root_dir):
        lines.append(f"SOURCE {script.resolve().as_posix()};")
    return "\n".join(lines) + "\n"


def build_mysql_command(config: MysqlPrepareConfig) -> list[str]:
    return [
        config.client,
        "--default-character-set=utf8mb4",
        "--host",
        config.host,
        "--port",
        str(config.port),
        "--user",
        config.user,
    ]


def execute_bootstrap_sql(root_dir: Path, config: MysqlPrepareConfig) -> subprocess.CompletedProcess[str]:
    env = os.environ.copy()
    if config.password:
        env["MYSQL_PWD"] = config.password

    return subprocess.run(
        build_mysql_command(config),
        input=build_bootstrap_sql(root_dir, config),
        text=True,
        capture_output=True,
        env=env,
        check=False,
    )


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Prepare the Gaokao H5 MySQL schema and seed data.")
    parser.add_argument("--execute", action="store_true", help="Execute the bootstrap SQL with the mysql client.")
    parser.add_argument("--database", help="MySQL database name. Defaults to GAOKAO_H5_MYSQL_DATABASE or gaokao_h5.")
    parser.add_argument("--host", help="MySQL host. Defaults to GAOKAO_H5_MYSQL_HOST or 127.0.0.1.")
    parser.add_argument("--port", type=int, help="MySQL port. Defaults to GAOKAO_H5_MYSQL_PORT or 3306.")
    parser.add_argument("--user", help="MySQL user. Defaults to GAOKAO_H5_MYSQL_USER or root.")
    parser.add_argument(
        "--password",
        help="MySQL password. Prefer GAOKAO_H5_MYSQL_PASSWORD so the password is not stored in shell history.",
    )
    parser.add_argument("--client", help="mysql client executable. Defaults to GAOKAO_H5_MYSQL_CLIENT or mysql.")
    parser.add_argument("--root", type=Path, default=Path(__file__).resolve().parents[1], help="Project root directory.")
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    env_config = MysqlPrepareConfig.from_env()
    config = MysqlPrepareConfig(
        database=args.database or env_config.database,
        host=args.host or env_config.host,
        port=args.port or env_config.port,
        user=args.user or env_config.user,
        password=args.password if args.password is not None else env_config.password,
        client=args.client or env_config.client,
    )

    root_dir = args.root.resolve()
    bootstrap_sql = build_bootstrap_sql(root_dir, config)
    if not args.execute:
        command_preview = " ".join(build_mysql_command(config))
        print("Dry run only. Review this bootstrap SQL, then rerun with --execute when the MySQL target is ready.")
        print(f"mysql command: {command_preview}")
        print()
        print(bootstrap_sql)
        return 0

    result = execute_bootstrap_sql(root_dir, config)
    if result.stdout:
        print(result.stdout, end="")
    if result.stderr:
        print(result.stderr, end="")
    return result.returncode


if __name__ == "__main__":
    raise SystemExit(main())
